site_name: Ritza Style Guide
site_url: https://styleguide.ritza.co

nav:
    - Welcome: index.md
    - 'Writing guidelines': 
        - 'Goals and principles': goals-principles.md
        - 'Voice and tone': voice-tone.md
        - 'Structure': structure.md
        - 'Things to avoid': things-to-avoid.md

theme:
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
  name: material
  custom_dir: overrides
  logo: assets/ritzalogo.png

  palette:
    primary: red

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  generator: false
