site_name: Ritza Style Guide
site_url: https://styleguide.ritza.co

theme:
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
  name: material
  custom_dir: overrides
  logo: assets/ritzalogo.png

  palette:
    primary: red

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details

extra:
  generator: false
